deployment:
  tasks:
    # Limpa o public_html
    - /bin/rm -rf /home/jorge69/public_html/*

    # Copia os arquivos jรก buildados (dist) para o public_html
    - /bin/cp -R /home/jorge69/repo/dist/* /home/jorge69/public_html/
